name: lqt
version: 0.1.0
copyright:
  - name: NONE
    url: https://github.com/jdwor/LQT
architectures:
  - x86_64
structured_readme:
  description: |-
    LQT is an R implementation of the lesion quantification toolkit, based on the paper “Lesion Quantification Toolkit: A MATLAB software tool for estimating grey matter damage and white matter disconnections in patients with focal brain lesions” by Griffis et al. The LQT is “a publicly available software package for quantifying the structural impacts of focal brain lesions. It uses atlas-based approaches to estimate parcel-level grey matter lesion loads and multiple measures of white matter disconnection severity that include tract-level disconnection measures, voxel-wise disconnection maps, and parcel-wise disconnection matrices. The toolkit also estimates lesion-induced increases in the lengths of the shortest structural paths between parcel pairs, which provide information about changes in higher-order structural network topology.”

    The R package creates data structures necessary for applying the methods directly to MNI-registered lesion maps from either a single patient or a full study. The package then allows the user to create figures for visualization and summary, and to compile analysis-ready datasets for research.
  example: |-
    # Example usage

    ```bash
    # Run R interactively in the container
    docker run --rm -it lqt:0.1.0 R

    # Execute an R script
    docker run --rm -v /path/to/your/script.R:/script.R lqt:0.1.0 Rscript /script.R

    # Test that the package is available
    docker run --rm lqt:0.1.0 R --slave -e "library(LQT); cat('LQT is available!\\n')"

    ```
  documentation: |-
    This container includes:
    - R
    - The R package LQT from https://github.com/jdwor/LQT
    - Additional CRAN packages: none
    - Additional Bioconductor packages: none
    - System dependencies: none
    - Deployed scripts: none

    For detailed package documentation, see: https://github.com/jdwor/LQT
  citation: "Please cite the original authors of the LQT package when using this container. Repository: https://github.com/jdwor/LQT"
readme: |-
  ----------------------------------
  ## lqt/{{ context.version }} ##

  LQT is an R implementation of the lesion quantification toolkit, based on the paper “Lesion Quantification Toolkit: A MATLAB software tool for estimating grey matter damage and white matter disconnections in patients with focal brain lesions” by Griffis et al. The LQT is “a publicly available software package for quantifying the structural impacts of focal brain lesions. It uses atlas-based approaches to estimate parcel-level grey matter lesion loads and multiple measures of white matter disconnection severity that include tract-level disconnection measures, voxel-wise disconnection maps, and parcel-wise disconnection matrices. The toolkit also estimates lesion-induced increases in the lengths of the shortest structural paths between parcel pairs, which provide information about changes in higher-order structural network topology.”

  The R package creates data structures necessary for applying the methods directly to MNI-registered lesion maps from either a single patient or a full study. The package then allows the user to create figures for visualization and summary, and to compile analysis-ready datasets for research.

  Example:
  ```
  # Example usage

  ```bash
  # Run R interactively in the container
  docker run --rm -it lqt:0.1.0 R

  # Execute an R script
  docker run --rm -v /path/to/your/script.R:/script.R lqt:0.1.0 Rscript /script.R

  # Test that the package is available
  docker run --rm lqt:0.1.0 R --slave -e "library(LQT); cat('LQT is available!\\n')"

  ```
  ```

  More documentation can be found here: This container includes:
  - R
  - The R package LQT from https://github.com/jdwor/LQT
  - Additional CRAN packages: none
  - Additional Bioconductor packages: none
  - System dependencies: none
  - Deployed scripts: none

  For detailed package documentation, see: https://github.com/jdwor/LQT

  Citation:
  ```
  Please cite the original authors of the LQT package when using this container. Repository: https://github.com/jdwor/LQT
  ```

  To run container outside of this environment: ml lqt/{{ context.version }}

  ----------------------------------
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - install:
        - r-base
        - r-base-dev
    - run:
        - R --slave -e "if (!require('devtools', quietly = TRUE)) install.packages('devtools', repos='https://cloud.r-project.org/'); devtools::install_github('jdwor/LQT', dependencies=TRUE, upgrade='never'); cat('Installed LQT from GitHub\n')"
    - test:
        name: verify_r_installation
        script: |-
          # Test R installation
          R --version
          echo "Testing R package installation..."
          R --slave -e "
            # Check R version
            cat('R version:', R.version.string, '\n')
            
            # Test main package
            tryCatch({
              library(LQT)
              cat('Successfully loaded LQT\n')
              
              # Try to get package info
              pkg_info <- packageDescription('LQT')
              if (!is.na(pkg_info)) {
                cat('Package version:', pkg_info[['Version']], '\n')
                cat('Package title:', pkg_info[['Title']], '\n')
              }
            }, error = function(e) {
              cat('Warning: Could not load LQT:', e[['message']], '\n')
              cat('Installed packages:\n')
              print(installed.packages()[,c('Package', 'Version')])
            })
            
            # List key installed packages
            key_packages <- c()
            if (length(key_packages) > 0) {
              cat('Checking additional packages:\n')
              for (pkg in key_packages) {
                if (require(pkg, character.only = TRUE, quietly = TRUE)) {
                  cat('  ✓', pkg, '\n')
                } else {
                  cat('  ✗', pkg, '(not found)\n')
                }
              }
            }
          "
categories:
  - structural imaging
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAABAJJREFUSEulln1IXXUYxz+/e71XSd00h8gkKqJW4vBtipRarCwJ2qQNpqzVqEkJQdAfFRHDf1YG2h+FEkEIYs2c2F324q0173Q357xO8zXTjcxNUpuOcLte0/OL8+Lx3HvVqB04cF6e83ye5/t7fs9zhOObQSmkREoJayeY1+pz873luWarmikKQjO3fG/xI5xfDxiWusFmoDW49j4UZHEY+r1wtP4cBDCzsEQY5jAkw6DMFSUoAOFUAUbkWqohBqYUVqmsUhr2m0kpHKf7wiS6Hc1DQTpgg8W1LuKGmi/5IeBHRt0BEQ69KNQjVCKH65IOWFlB6W5nteot3RCwv/4uYk8B2O26g8ASypAP6W4maW6KjIwMurq6uJGSjdi7D3HPLqTNFrwGji97dbQKuHCWPF8bHo+H/Px8unKe1gHqR6rzzjYevdxDa2sr0dHRZiALCwsU7SvGl/IIIisfHE6tGtU1FREtPn0frKwgL3pMQEFBAT/tKYKsfIQQKMO9pLY30+/tYHp6murqampra8nOzsblchEfH8/O3RnMPXMU7k81sxCOFl+QRHm9bi2DNYAW0dItFFc9njdeITc3l7i4OG5tS0Dcuws57OOBpETGxsZoaGjgeZcH8XixloV6iIjmi6ZEsrudvEvfrwOyntIy4PoMSt0HzJ5pZXZ2ltTDL2E78hrcmYi89htKXTXzPeeZnJwk89U3EQeOQcw2HeAwAJpEGwBEZh7yjymUj0+wONjLwMAAD7/zPrYDL2rVI6euIE/Xc/W7FhYXF3nwcBni0MuwPUErDBFxqtuUSPacC8rAm/kkKoCZqyifvMd054/ExsYSW3QQsf8IcqQPWVelRer3+7WK2vv2CWwHjyFjthsSNV1Yl0hd5L4fTIm8scnwUDrcXES2f4X7oyoKCwtJS0tj8OYKO/6ao62tjaamJiorKykpKaHJ70Q88Sw4Iw3AF13BgP4zGqCiooKhoSGzFEdHR1leXmZ8fJz5+XlKS0uZmJhgeHiYqKgorbKSk5MR5cdhdw4IYUikAoyNpklkAEzPxoXb7abouaMU5+XS2NhIZKQeoXoEAgGcTidlZWV8etaLraQcedd9+j6wn/RKrcmpi9xzDuXD46G+zXuR8xjcuI78dZCUlBTS09Pp7+9nZGSEmpoaLfNTk38i9r8AcQmGRCe9egbKKnJmGjlzzegna73F0v+jY2BHEvL3y3DlF1j9W68WewSy41utpYhD5bDz7vWNZv/8fHCzC2lW/zpgVHs1wPlZrZ2QmGzqr5fpZ51aiFuOxtuYF8Le0BGUQRhog4z+y7wIA4T28y1n9GYT0Dr07fWe8KGvaxZ+bvH3EPRTsBXAavi/ZrThfE3qfwDw/n/IevKjrAAAAABJRU5ErkJggg==
